### ISSUE TITLE
Error message for decryption password can be more friendly

### ISSUE THREAD

**Issue by wschoot** [Brainsupporter/Issues#2]
![image](https://github.com/user-attachments/assets/3beb86be-64d8-4968-8707-c946aaa73468)

Right now, when you fail to reproduce the encryption password (after a fun night out with the nerds!), the error message show can be more friendly. Only showing the second part should do it.

**Comment by raseesink** [comment]
Agreed

**Comment by raseesink** [comment]
This is improved on the canary enviroment, pending release.

Btw, canary is a an enviroment used for testing, using production data.
https://gray-tree-01c1bf703-canary.westeurope.2.azurestaticapps.net/

**Comment by raseesink** [comment]
This is fixed on the canary enviroment, pending release.

Btw, canary is a an enviroment used for testing, using production data.
https://gray-tree-01c1bf703-canary.westeurope.2.azurestaticapps.net/

We also have an acceptance enviroment which does not use production data
https://blue-plant-0c46d0403.1.azurestaticapps.net/

**Comment by raseesink** [comment]
This has been released to production
