### ISSUE TITLE
after completing a task, the presented task list doesn't show contexts anymore

### ISSUE THREAD

**Issue by tjeerdhans** [Brainsupporter/Issues#5]
See image. As opposed to `lt`, which does show the contexts.
 
![image](https://github.com/user-attachments/assets/e4015321-2d22-4f6d-b2ae-b9a7745ae08d)

**Comment by nschmoller** [comment]
You are right. We should show the context for the task list when no context is selected.

**Comment by nschmoller** [comment]
This is solved in the development version and will be available after the next release.

We simplified when the contexts is being shown on tasks. From now on the context of the task is shown when no context is selected in the dropdown, both in the task list and for the output of the lt-command.

**Comment by raseesink** [comment]
This has been released to production
