### ISSUE TITLE
Long lines should be wrapped (and discouraged)

### ISSUE THREAD

**Issue by wschoot** [Brainsupporter/Issues#6]
Your tasks should be small and concrete so a discouragement might be in place. But, if longer tasks are there, wrap then nicely

![image](https://github.com/user-attachments/assets/f0425eb4-503c-4583-ae71-a436231aecf2)

EDIT: It works well when there are spaces (ie positions where a linebreak is appropriate)

**Comment by nschmoller** [comment]
You are right about the wrapping. We will change that.

**Comment by nschmoller** [comment]
Fixed and released to production.

**Comment by wschoot** [comment]
Yes, works great. Thanks
