### ISSUE TITLE
Importer is pretty verbose on invalid imports

### ISSUE THREAD

**Issue by wschoot** [Brainsupporter/Issues#7]
![image](https://github.com/user-attachments/assets/f464f181-256e-4aeb-813a-ecbec94445f1)

I realise this zip wasn't a real zip but boy, oh boy, it wasn't nice in telling me so!

**Comment by nschmoller** [comment]
We should add a nice error message here.

**Comment by raseesink** [comment]
This is improved on the canary enviroment, pending release.

Btw, canary is a an enviroment used for testing, using production data.
https://gray-tree-01c1bf703-canary.westeurope.2.azurestaticapps.net/

We also have an acceptance enviroment which does not use production data
https://blue-plant-0c46d0403.1.azurestaticapps.net/

**Comment by raseesink** [comment]
This has been released to production
