### ISSUE TITLE
It's possible to add an empty context

### ISSUE THREAD

**Issue by nschmoller** [Brainsupporter/Issues#8]
If you add a task with the context `@ ` (with a space after the @-sign) it will create an empty context that you cannot select. See screenshot 1 for the command and screenshot for how it looks in the context dropdown. If you select the empty context nothing happens.

<img width="819" alt="Screenshot 2024-11-25 at 20 29 54" src="https://github.com/user-attachments/assets/f4c807ce-860a-4efd-82da-38a7290d3a46">
<img width="817" alt="Screenshot 2024-11-25 at 20 30 08" src="https://github.com/user-attachments/assets/3e543519-1a57-45cf-9cd4-8f9a83ce1fe7">

**Comment by raseesink** [comment]
This is fixed, pending release.

**Comment by raseesink** [comment]
This is released to production 🚢
